[tools]
"cargo:xan" = "0.46.2"
"pipx:beets" = { version = "latest", pipx_args = "--python 3.13", uvx_args = "--python 3.13" }
usage = "latest"

[settings]
experimental = true
# TODO: Once this setting can actually be set in ~/.config/mise/conf.d/*.toml, migrate it to there;
# try using templates to allow them to concatenate. Something like:
# idiomatic_version_file_enable_tools = {{ exec(command = 'mise config get settings.idiomatic_version_file_enable_tools | sed "s/]/\"node\"]/"') }}
idiomatic_version_file_enable_tools = ["java", "node", "ruby"]

[settings.python]
# Use uv's venv
# mise sync python --uv could also be useful
uv_venv_auto = true
[settings.pipx]
uvx = true
